services:
  backend:
    build:
      context: .
      dockerfile: ./docker/backend/produccion/Dockerfile
    container_name: ${APP_NAME}_backend
    ports:
      - "8000:8000"
    networks:
      - network
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      DJANGO_ENV: produccion
      SECRET_KEY: ${SECRET_KEY}
      API: ${API}
    
  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend/produccion/Dockerfile
    container_name: ${APP_NAME}_frontend
    ports:
      - "80:80"
    networks:
      - network
    environment:
      VITE_API_URL: ${VITE_API_URL}
  
networks:
  network:
    name: ${APP_NAME}_network
    driver: bridge
  
