name: Production Deploy – Django to Heroku & React to Vercel

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-build-deploy:
    runs-on: ubuntu-latest

    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      POSTGRES_DB: test_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install backend dependencies
        run: |
          cd backend
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run backend migrations
        run: |
          cd backend
          python manage.py makemigrations --noinput
          python manage.py migrate --noinput

      # - name: Run backend tests
      #   run: |
      #     cd backend
      #     pytest

      - name: Check Python syntax (pycodestyle)
        run: |
          cd backend
          pycodestyle --ignore=E501 --statistics .

      - name: Install frontend dependencies
        run: |
          cd frontend
          yarn install

      # - name: Run frontend tests
      #   run: |
      #     cd frontend
      #     yarn test --watchAll=false

      - name: Build frontend
        run: |
          cd frontend
          yarn build

      # - name: Deploy to Heroku
      #   uses: akhileshns/heroku-deploy@v3.12.12
      #   with:
      #     heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
      #     heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
      #     heroku_email: ${{ secrets.HEROKU_EMAIL }}

      # - name: Deploy to Vercel
      #   env:
      #     VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      #     VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      #     VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      #   run: |
      #     cd frontend
      #     npx vercel --prod --confirm --token $VERCEL_TOKEN --scope $VERCEL_ORG_ID --project $VERCEL_PROJECT_ID
